# Generated by Django 5.0.6 on 2024-07-08 01:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_solditems_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='color',
        ),
    ]
