# Generated by Django 5.0.6 on 2024-07-08 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_remove_category_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='solditems',
            name='price',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
